name:                ljpd
version:             0.1.0.0
github:              "madf/ljpd"
license:             BSD3
author:              "Maksym Mamontov"
maintainer:          "ljpd@madf.info"
copyright:           "2022 Maksym Mamontov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/madf/ljpd#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ljpd-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ljpd
    - text
    - bytestring
    - aeson
    - http-conduit
    - http-types
    - regex-tdfa
    - download
    - directory
    - filepath

tests:
  ljpd-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ljpd
